### ISSUE TITLE
CPI実行後画像が一つ隠れている

### ISSUE THREAD

**Issue by jctk** [snagahiro/CPI_script#7]
CPI実行後にView ExplorerではImage01とstacked_ccの二枚の画像があることになっている。
表示されているのはstacked_ccの一枚
実用上問題は感じていません。Issueとしては軽微。
![image](https://user-images.githubusercontent.com/52247294/152996441-2d9e1980-ca22-4069-beb9-d759f7af8545.png)

**Comment by dabokun** [comment]
報告どうもありがとうございます。

Scriptをいじれる場合、233行目https://github.com/snagahiro/CPI_script/blob/89da3aace16298245295133c3f1a9df06915cfed/coldpixelinterpolation.js#L233 に stackedImageWin.forceClose();
と追記することでこの問題は解決するはずです。次の版で改善させていただきます。


また本件とは関係ありませんが、stacked_cc という名前はプログラム上の本来の意図とは異なっている（stacked_ccはcosmetic correction後のファイル名を指すが、PixInsight上のウィンドウで表示されているのはクールファイルのViewである）のでIDも変更できるならば変更する必要があるかと思われます。これについても次以降の版で改善を検討します。

**Comment by jctk** [comment]
Versoin 0.1.2 で View Explorer に Image01 が残されていないことを確認しました。
